
package admin_web_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminWebServiceImplService", targetNamespace = "http://webservice.polytech.fr/", wsdlLocation = "http://localhost:8080//AdminWebServiceImplService?wsdl")
public class AdminWebServiceImplService
    extends Service
{

    private final static URL ADMINWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADMINWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.polytech.fr/", "AdminWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080//AdminWebServiceImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADMINWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdminWebServiceImplService() {
        super(__getWsdlLocation(), ADMINWEBSERVICEIMPLSERVICE_QNAME);
    }

    public AdminWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ADMINWEBSERVICEIMPLSERVICE_QNAME);
    }

    public AdminWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminWebService
     */
    @WebEndpoint(name = "AdminWebServiceImplPort")
    public AdminWebService getAdminWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.polytech.fr/", "AdminWebServiceImplPort"), AdminWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminWebService
     */
    @WebEndpoint(name = "AdminWebServiceImplPort")
    public AdminWebService getAdminWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.polytech.fr/", "AdminWebServiceImplPort"), AdminWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ADMINWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADMINWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
