
package rooms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param date
     * @param number
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "QueryRoomNumber", action = "http://tempuri.org/IService1/QueryRoomNumber")
    @WebResult(name = "QueryRoomNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryRoomNumber", targetNamespace = "http://tempuri.org/", className = "rooms.QueryRoomNumber")
    @ResponseWrapper(localName = "QueryRoomNumberResponse", targetNamespace = "http://tempuri.org/", className = "rooms.QueryRoomNumberResponse")
    public Boolean queryRoomNumber(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        Integer number);

}
