
package organiser_web_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrganiserWebServiceImplService", targetNamespace = "http://webservice.polytech.fr/", wsdlLocation = "http://localhost:8080/webservices/OrganiserWebServiceImpl?wsdl")
public class OrganiserWebServiceImplService
    extends Service
{

    private final static URL ORGANISERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORGANISERWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ORGANISERWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.polytech.fr/", "OrganiserWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservices/OrganiserWebServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORGANISERWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ORGANISERWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OrganiserWebServiceImplService() {
        super(__getWsdlLocation(), ORGANISERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public OrganiserWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORGANISERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrganiserWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ORGANISERWEBSERVICEIMPLSERVICE_QNAME);
    }

    public OrganiserWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORGANISERWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrganiserWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganiserWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrganiserWebService
     */
    @WebEndpoint(name = "OrganiserWebServiceImplPort")
    public OrganiserWebService getOrganiserWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.polytech.fr/", "OrganiserWebServiceImplPort"), OrganiserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrganiserWebService
     */
    @WebEndpoint(name = "OrganiserWebServiceImplPort")
    public OrganiserWebService getOrganiserWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.polytech.fr/", "OrganiserWebServiceImplPort"), OrganiserWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORGANISERWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ORGANISERWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ORGANISERWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
