
package log_in_web_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogInWebServiceImplService", targetNamespace = "http://webservice.polytech.fr/", wsdlLocation = "http://localhost:8080//LogInWebServiceImplService?wsdl")
public class LogInWebServiceImplService
    extends Service
{

    private final static URL LOGINWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOGINWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.polytech.fr/", "LogInWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080//LogInWebServiceImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOGINWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LogInWebServiceImplService() {
        super(__getWsdlLocation(), LOGINWEBSERVICEIMPLSERVICE_QNAME);
    }

    public LogInWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogInWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOGINWEBSERVICEIMPLSERVICE_QNAME);
    }

    public LogInWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogInWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogInWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogInWebService
     */
    @WebEndpoint(name = "LogInWebServiceImplPort")
    public LogInWebService getLogInWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.polytech.fr/", "LogInWebServiceImplPort"), LogInWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogInWebService
     */
    @WebEndpoint(name = "LogInWebServiceImplPort")
    public LogInWebService getLogInWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.polytech.fr/", "LogInWebServiceImplPort"), LogInWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOGINWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOGINWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
